# Generated by Django 4.2.11 on 2024-07-26 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=10, unique=True)),
                ('jenis_kelamin', models.CharField(choices=[('l', 'Laki - Laki'), ('p', 'Perempuan')], max_length=2)),
                ('jurusan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('sks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(max_length=2)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.mahasiswa')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.matakuliah')),
            ],
        ),
    ]
