# Generated by Django 4.2.11 on 2024-07-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_matakuliah_rumpun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='kode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
