# Generated by Django 4.2.11 on 2024-07-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0003_alter_matakuliah_kode'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tugas', models.DateField()),
                ('uts', models.DateField()),
                ('uas', models.DateField()),
                ('dpna', models.DateField()),
            ],
        ),
    ]
