# Generated by Django 4.2.11 on 2024-07-27 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0004_jadwalpenilaian'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobotPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kehadiran', models.IntegerField()),
                ('tugas', models.IntegerField()),
                ('uts', models.IntegerField()),
                ('uas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nidn', models.CharField(max_length=20, unique=True)),
                ('nuptk', models.CharField(max_length=20, unique=True)),
                ('bidang_keahlian', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeteranganMataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('I', 'I'), ('I', 'I'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=5)),
                ('kelas', models.CharField(blank=True, max_length=5, null=True)),
                ('dosen_pembina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akademik.dosen')),
                ('dosen_penanggung_jawab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keterangan_kuliahs', to='akademik.dosen')),
            ],
        ),
    ]
