# Generated by Django 4.2.11 on 2024-07-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0005_bobotpenilaian_dosen_keteranganmatakuliah'),
    ]

    operations = [
        migrations.AddField(
            model_name='keteranganmatakuliah',
            name='matakuliah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akademik.matakuliah'),
        ),
        migrations.AlterField(
            model_name='keteranganmatakuliah',
            name='semester',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=5),
        ),
    ]
