# Generated by Django 4.2.11 on 2024-07-27 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0006_keteranganmatakuliah_matakuliah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keteranganmatakuliah',
            name='periode',
            field=models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='keteranganmatakuliah',
            name='tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PesertaMataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.mahasiswa')),
                ('matakuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.keteranganmatakuliah')),
            ],
        ),
    ]
