# Generated by Django 4.2.11 on 2024-07-28 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0007_keteranganmatakuliah_periode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keteranganmatakuliah',
            name='semester',
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=5)),
                ('matakuliah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akademik.matakuliah')),
            ],
        ),
    ]
