# Generated by Django 4.2.11 on 2024-07-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0008_remove_keteranganmatakuliah_semester_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='matakuliah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='akademik.matakuliah'),
        ),
    ]
