# Generated by Django 4.2.11 on 2024-07-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0009_alter_semester_matakuliah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='matakuliah',
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matakuliahs', to='akademik.semester'),
        ),
    ]
